### ISSUE TITLE
Question: Does it support android library publishing?

### ISSUE THREAD

**Issue by emartynov** [joffrey-bion/gradle-kotlin-publish-plugin#5]
I assume it should be similar to the java library except `aar` uploaded instead `jar`. However, the android plugin is applied in addition to the kotlin.

**Comment by joffrey-bion** [comment]
It depends on what you mean. I haven't tested this plugin with android libraries publications.

Technically the plugin should work as far as Dokka setup is concerned. However, I don't know if android publications are automatically setup. I know the MPP plugin automatically sets up publications for all source sets (and platforms). And I know the JS and JVM plugins don't, so this plugin auto-registers the publications for them.

So if the android plugin automatically sets things up, this kotlin publish plugin can automatically add Dokka setup. If the android plugin doesn't setup publications, you would have to do that by hand, and then this plugin will setup Dokka automatically.

Please let me know if there is anything I can add here. And don't hesitate to contribute if you find what's missing :)

**Comment by joffrey-bion** [comment]
Nite that for Android applications (not libraries) this plugin might not be that useful, by the way. It's mostly for sources jars and Dokka setup, which are mostly useful for libraries. It doesn't help with artifacts upload.

**Comment by emartynov** [comment]
Ah, sorry to jump without clearing my intent.
We have an android library and we set up already documents, sources and binary uploads. This plugin could remove some of our gradle lines (I wonder if my team will want it).

However, for other projects, it might be beneficial. I will use this plugin locally first and give feedback here.

Closing this ticket until I have something valuable.
